=== lucianoalvarez22/Lenguaje-de-Marcas/Ejercicios_Schema/catalogo_libros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="catalogoLibro">
    <xs:complexType>
    <xs:sequence>
        <xs:element ref="libro" minOccurs="0" maxOccurs="unbounded"/> <!-- He puesto minimo 0 y maximo muchos porque libros puede aparecer muchas veces -->
        </xs:sequence>
    </xs:complexType>
  </xs:element>



  <xs:element name="libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="tipoNombre"/>
        <xs:element name="autor" type="tipoNombre" minOccurs="1" maxOccurs="unbounded"/> <!-- En este caso he puesto minimo 1 y maximo muchos porque en el DTD dice que el autor puede aparecer 1 o mas veces -->
        <xs:element ref="fecha"/>
        <xs:element name="ISBN" type="tipoISBN"/>
        <xs:element name="editor" type="tipoNombre"/>
      </xs:sequence>
      
      <xs:attribute name="categoria" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="noficcion"/>
            <xs:enumeration value="ficcion"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      
      <xs:attribute name="enstock" default="false">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      
      <xs:attribute name="revisor" type="xs:string" default=""/>
      
    </xs:complexType>
  </xs:element>
  
  <!-- La restriccion de tipoNombre la pongo una vez para que haga efecto a todos los elementos que tenga como type "tipoNombre" -->
  <xs:simpleType name="tipoNombre">
        <xs:restriction base="xs:string">
        <xs:minLength value="0"/> <!-- Restriccion de minimo de caracteres 0 y maximo de 100 -->
        <xs:maxLength value="100"/>
        </xs:restriction>
  </xs:simpleType>
  
  <!-- He hecho lo mismo con tipoISBN para que pueda ser usado por mas elementos -->
   <xs:simpleType name="tipoISBN">
        <xs:restriction base="xs:string">
        <xs:minLength value="13"/>
        <xs:maxLength value="17"/>
        </xs:restriction>
  </xs:simpleType>   


  <xs:element name="fecha">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="mes" type="tipoMes" minOccurs="0"/> <!-- En este caso también le he puesto un tipoMes y además un minimo 0 ya que el DTD dice que el mes puede ser opcional -->
        <xs:element name="año" type="tipoAño"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
  <xs:simpleType name="tipoMes">
        <xs:restriction base="xs:positiveInteger">
        <xs:minInclusive value="1"/> <!-- Restriccion para decir que el min de numeros es el 1(incluido) y el maximo el 12(incluido) -->
        <xs:maxInclusive value="12"/>
        </xs:restriction>
  </xs:simpleType>  

    <xs:simpleType name="tipoAño">
        <xs:restriction base="xs:positiveInteger">
        <xs:minInclusive value="1900"/>
        <xs:maxInclusive value="2021"/>
        </xs:restriction>
    </xs:simpleType>  

</xs:schema>

=== lucianoalvarez22/Lenguaje-de-Marcas/Ejercicios_Schema/catalogo_libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogoLibro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogo_libros.xsd">

<libro categoria="ficcion" enstock="true">
<titulo>Los hombres que no amaban a las mujeres</titulo>
<autor>Stieg Larsson</autor>
<fecha>
<año>2008</año>
</fecha>
<ISBN>978-84-233-4044-6</ISBN>
<editor>Destino</editor>
</libro>

<!-- Segun el ejercicio 6, el primer elemento libro tiene como atributos categoria y enstock es true. Elementos titulo, autor, fecha, solo tiene año, ISBN  y editor -->

<libro categoria="noficcion" enstock="false" revisor="Carlos Montes">
<titulo>Java a través de ejemplos</titulo>
<autor>Jesus Bobadillo</autor>
<autor>Adela Sancho</autor>
<fecha>
<año>2003</año>
</fecha>
<ISBN>84-7897-549-7</ISBN>
<editor>Ra-ma</editor>
</libro>

<!-- Segun el ejercicio 6, a diferencia con el anterior, tiene como atributo enstock en FALSE, ńo sé si hacía falta ponerlo o no porque por defecto dice que es false -->
<!-- También tiene revisor como atributo -->
<!-- Y otra diferencia es que, en este caso, hay dos elementos autor ya que el libro cuenta como mas de un autor. Por lo demás es todo igual al anterior. Tampoco tiene mes -->

</catalogoLibro>
