=== lucianoalvarez22/Lenguaje-de-Marcas/Ejercicios_Schema/Ejercicio08Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="biblioteca">

    <xs:complexType>
      <xs:sequence>
        <xs:element ref="libro" minOccurs="2" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="autor" type="xs:string"  maxOccurs="3"/>
        <xs:element name="editorial" type="tipoEditorial"/> <!-- Le he quitado el MIN y el MAX para que por defecto tenga que aparecer -->
        <xs:element name="edicion" type="xs:string" minOccurs="0"/> <!--La edicion no es un elemento obligatorio, lo he puesto como opcional con el minOccurs=0 -->
        <xs:element name="fecha" type="xs:string"/>
        <xs:element name="isbn" type="tipoISBN"/>
        <xs:element name="donacion" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="caracteristicas"/> <!-- Elemento caracteristica que desarrollaré mas abajo -->
        <xs:element name="ubicacion" type="tipoUbicacion"/>
      </xs:sequence>
      
      <!-- El atributo codigo es unico y esta formado por tres caracteres -->
      <xs:attribute name="codigo" use="required">
       <xs:simpleType>
       <xs:restriction base="xs:ID">
       <xs:minLength value="3"/>
        <xs:maxLength value="3"/>
       </xs:restriction>
       </xs:simpleType>
      </xs:attribute>
      
      <xs:attribute name="titulo" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

<!-- tipoEditorial le he puesto como atributo nombre y restriccion para que solo se puede elegir entre esas dos opciones -->
  <xs:complexType name="tipoEditorial">
      <xs:attribute name="nombre" use="required">
      <xs:simpleType>
      <xs:restriction base="xs:string">
         <xs:enumeration value="Lengua de trapo"/>
         <xs:enumeration value="Libros del KO"/>
      </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
   </xs:complexType>
   
   <!-- El tipoISBN le he creado una restriccion de PATTERN para que concuerde con lo que pide el ejercicio nn-nn-nnnn -->
   <xs:simpleType name="tipoISBN">
        <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{2}[\-]{1}[0-9]{2}[\-]{1}[0-9]{4}"/>
        </xs:restriction>
  </xs:simpleType>   
   
   <!-- Elemento caracteristica con una secuencia de dos elementos, numpaginas y calidad -->
   <xs:element name="caracteristicas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="numPaginas" type="tiponumPaginas"/> 
        <xs:element name="calidad" type="tipoCalidad"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- He creado el tiponumPaginas y dentro una restriccion de positiveinteger con un min incluido y un max incluido -->
  <xs:simpleType name="tiponumPaginas">
        <xs:restriction base="xs:positiveInteger">
        <xs:minInclusive value="160"/> 
        <xs:maxInclusive value="430"/>
        </xs:restriction>
  </xs:simpleType>  
  
  <!-- En tipo calidad he añadido un atributo que será formato y se pondrá poner si es rustica o de bolsillo. El tipoCalidad es complejo por llevar atributo -->
  <xs:complexType name="tipoCalidad">
      <xs:attribute name="formato" use="required">
      <xs:simpleType>
      <xs:restriction base="xs:string">
         <xs:enumeration value="rustica"/>
         <xs:enumeration value="bolsillo"/>
      </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
   </xs:complexType>
   
   

    <xs:complexType name="tipoUbicacion">
      <xs:attribute name="sede" use="required">
      <xs:simpleType>
      <xs:restriction base="xs:string">
         <xs:enumeration value="norte"/>
         <xs:enumeration value="sur"/>
      </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
   </xs:complexType>


</xs:schema>

=== lucianoalvarez22/Lenguaje-de-Marcas/Ejercicios_Schema/Ejercicio08Schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio08Schema.xsd">


<libro codigo="L01" titulo="La sombra del viento">
<autor>Carlos Ruiz Zafon</autor>
<editorial nombre="Lengua de trapo"/>
<edicion>5</edicion>
<fecha>25/02/2023</fecha>
<isbn>23-59-6789</isbn>
<caracteristicas>
<numPaginas>430</numPaginas>
<calidad formato="bolsillo"/>
</caracteristicas>
<ubicacion sede="norte"/>
</libro>

<libro codigo="L02" titulo="El prisionero del cielo">
<autor>Carlos Ruiz Zafon</autor>
<editorial nombre="Libros del KO"/>
<fecha>26/02/2023</fecha>
<isbn>02-43-0689</isbn>
<donacion>40€</donacion>
<caracteristicas>
<numPaginas>350</numPaginas>
<calidad formato="rustica"/>
</caracteristicas>
<ubicacion sede="sur"/>
</libro>


</biblioteca>
