=== lucianoalvarez22/Lenguaje-de-Marcas/Ejercicios_DTD/Ejercicio2DTD.dtd
<!ELEMENT geometria (forma+)>
<!ELEMENT forma (nombre, caracteristicas, numladoss)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT caracteristicas ((color, tipo)|descripciÃ³n)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT numlados (#PCDATA)>

 <!-- En numlados he puesto opcional porque en el xml hay una etiqueta numlados que aparece vacia -->
 <!-- en color, tipo y descripcion he puesto opcional porque he visto que dentro de caracteristica pueden aparecer o no -->

=== lucianoalvarez22/Lenguaje-de-Marcas/Ejercicios_DTD/Ejercicio2DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE geometria SYSTEM "Ejercicio2DTD.dtd">
<geometria>

<forma>
   <nombre>rombo</nombre>
   <caracteristicas>
      <color>naranja</color>
      <tipo>plana</tipo>
   </caracteristicas>
   <numlados>4</numlados>
</forma>

<forma>
   <nombre>rectángulo</nombre>
   <caracteristicas>
    <descripcion>El color elegido es el verde y el tipo es especial, adecuándose a lo solicitado.</descripcion>
   </caracteristicas>
   <numlados/>
</forma>

</geometria>
