=== lucianoalvarez22/Lenguaje-de-Marcas/Ejercicios_DTD/Ejercicio7DTD.dtd
<!ELEMENT ediciones (cabecera, tabla)>
<!ELEMENT cabecera (titulo, contenido, descripcion)>
  <!ATTLIST cabecera fecha CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT tabla (norte, centro, sur)>
<!ELEMENT norte (lib_vendidos)+>
  <!ATTLIST norte nombre CDATA #REQUIRED>
  <!ATTLIST lib_vendidos trimestre (1 | 2 | 3 | 4) #REQUIRED>
<!ELEMENT centro (lib_vendidos)+>
  <!ATTLIST centro nombre CDATA #REQUIRED>
  <!ATTLIST lib_vendidos trimestre (1 | 2 | 3 | 4) #REQUIRED>
<!ELEMENT sur (lib_vendidos)+>
  <!ATTLIST sur nombre CDATA #REQUIRED>
  <!ATTLIST lib_vendidos trimestre (1 | 2 | 3 | 4) #REQUIRED>
  <!ELEMENT lib_vendidos (#PCDATA)>

<!--La fecha lo he puesto como atributo de cabecera -->
<!-- El nombre lo he puesto como atributo en las etiquetas, norte, ,centro y sur-->
<!-- He puesto trimestre como atributo dentro de lib_vendido. Al validar el xml, me lo da por valido pero me pone 2 avisos -->

=== lucianoalvarez22/Lenguaje-de-Marcas/Ejercicios_DTD/Ejercicio7DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ediciones SYSTEM "Ejercicio7DTD.dtd">
<ediciones>

  <cabecera fecha="30/12/2009">
    <titulo>Ediciones</titulo>
    <contenido>Informe regional de ventas</contenido>
    <descripcion>Descripcion: informe de ventas para las regiones Norte, Centro y Sur</descripcion>
  </cabecera>
  <tabla>
      <norte nombre="Norte">
        <lib_vendidos trimestre="1">24000</lib_vendidos>
        <lib_vendidos trimestre="2">38600</lib_vendidos>
        <lib_vendidos trimestre="3">NO_INFO</lib_vendidos>
        <lib_vendidos trimestre="4">NO_INFO</lib_vendidos>
      </norte>
      
      <centro nombre="Centro">
        <lib_vendidos trimestre="1">NO_INFO</lib_vendidos>
        <lib_vendidos trimestre="2">16080</lib_vendidos>
        <lib_vendidos trimestre="3">25000</lib_vendidos>
        <lib_vendidos trimestre="4">29000</lib_vendidos>
      </centro>
      
      <sur nombre="Sur">
        <lib_vendidos trimestre="1">27000</lib_vendidos>
        <lib_vendidos trimestre="2">31400</lib_vendidos>
        <lib_vendidos trimestre="3">40100</lib_vendidos>
        <lib_vendidos trimestre="4">30000</lib_vendidos>
      </sur>
  </tabla>
</ediciones>
